In [ ]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv(r"C:\Users\Taksh\OneDrive\Desktop\ML_PROJECTS\ncr price predictor\data\raw\data of gurugram real Estate.csv")

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 19515 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          19515 non-null  str
 1   Status         19515 non-null  str
 2   Area           19515 non-null  int64
 3   Rate per sqft  19515 non-null  str
 4   Property Type  19515 non-null  str
 5   Locality       19515 non-null  str
 6   Builder Name   19515 non-null  str
 7   RERA Approval  19515 non-null  str
 8   BHK_Count      19515 non-null  float64
 9   Socity         19515 non-null  str
 10  Company Name   19515 non-null  str
 11  Flat Type      19515 non-null  str
dtypes: float64(1), int64(1), str(10)
memory usage: 4.5 MB

In [ ]:
data.head()

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor

In [ ]:
data.shape

(19515, 12)

In [ ]:
# issue 1-> price is stored as string
# issue 2-> Rate per sqft is string
# issue 3-> Property Type needs investigation (can drop this column cuz it already has the info we need)
# issue 4-> Socity typo

In [ ]:
data.duplicated().sum() # True means that row is a duplicate of a previous row. 
# if output =5 means there are 5 duplicate rows.
# helps remove duplicate columns.

np.int64(5292)

In [ ]:
data.nunique()# nunique() tells us how many unique values each categorical column has.
# This will help us decide encoding strategy.
# Flat type, status , rera approval (one hot)

Price            1758
Status              4
Area             2038
Rate per sqft    3928
Property Type    1848
Locality          245
Builder Name      725
RERA Approval       2
BHK_Count          25
Socity            967
Company Name      269
Flat Type           6
dtype: int64

In [ ]:
data["Price"].head(20)

0             10700000.0
1             14400000.0
2             10700000.0
3             40000000.0
4             24000000.0
5             63800000.0
6              4500000.0
7              4500000.0
8              9000000.0
9             74900000.0
10            19700000.0
11            80100000.0
12    13700000.000000002
13            22000000.0
14            15000000.0
15            44000000.0
16            12000000.0
17            52500000.0
18             4600000.0
19            30000000.0
Name: Price, dtype: str

In [ ]:
# so lets correct the data type of strings to integers(This is called data cleaning/type conversion.), 
# one hot encode , colums to drop and keep and we don't have to drop any rows since  all of them have data in them.

# Cardinality in data science means the number of unique values in a feature (column).

In [ ]:
# Keep:
# - Area → numerical, important
# - Rate per sqft → numerical after cleaning
# - Locality → important for real estate pricing
# - BHK_Count → important
# - Status → categorical (Ready to move / Under Construction)
# - RERA Approval → binary categorical
# - Flat Type → categorical
# - Builder Name → useful but high cardinality (needs handling)  (DROP)
# - Society → useful but high cardinality (needs handling)
# - Company Name → may be useful, needs investigation

# Drop:
# - Property Type → high cardinality and redundant
# - Price → target variable

In [ ]:
# df.duplicated().sum() -> So around 27% of your dataset is duplicated. That is quite high.

In [ ]:
data = data.drop_duplicates()

In [ ]:
data.shape

(14223, 12)

In [ ]:
# Raw dataset
#     |
#     ↓
# Remove duplicates ✅ 
#     |
#     ↓
# Fix data types 
#     |
#     ↓
# Handle categorical features
#     |
#     ↓
# Train model

# (Try removing features as well)

In [ ]:
# Lets inspect high cardinality columns
data["Builder Name"].value_counts().head(20)

Builder Name
properties for sale in Gurgaon       818
Property In Gurgaon                  810
home                                 803
Proptiger                            734
Sharma Prop                          490
WADHWA REALTORS                      299
Search My Property                   242
SBL                                  198
The Assetree                         165
Multi Home Realtors                  162
INFRAMANTRA INDIA PRIVATE LIMITED    154
Provident Capital                    151
Property Master                      134
Onkar real estate solutions          129
ETHOS PRO REALTORS                   123
Thirty Three Estates Developers      121
seller                               113
Surendra Realtors                    113
HOMZ SOLUTIONS                       110
Individual Agent                     109
Name: count, dtype: int64

In [ ]:
data["Socity"].value_counts().head(20)
# This will tell us whether these columns are valuable or mostly noise.

Socity
Outside Socity                   1277
 M3M Golf Estate                  509
 Krisumi Waterfall Residences     315
 Whiteland The Aspen              283
 Birla Navya Gurugram             252
 Godrej Air                       230
 Ireo Victory Valley              204
 M3M Capital                      201
 Elan The Presidential            183
 M3M M3M Crown                    160
 Sobha City Vista Residences      138
 M3M Merl                         126
 BPTP Terra                       114
 M3M Heights                      113
 M3M Sierra 68                    113
 Godrej Meridien                  112
 Sobha City                       109
 Godrej Aristocrat                108
 M3M Antalya Hills                107
 DLF The Crest                    103
Name: count, dtype: int64

In [ ]:
# This means:

# The same societies appear many times.
# Socity is not just random text.
# It carries meaningful information about the property's location and brand.

# For example:

# A flat in DLF The Crest is usually much more expensive than one in an unknown society.
# The model can learn these patterns.

In [ ]:
data[data["Socity"] == "DLF The Crest"]["Price"]

Series([], Name: Price, dtype: str)

In [ ]:
data["Builder Name"].value_counts().head(20)

Builder Name
properties for sale in Gurgaon       818
Property In Gurgaon                  810
home                                 803
Proptiger                            734
Sharma Prop                          490
WADHWA REALTORS                      299
Search My Property                   242
SBL                                  198
The Assetree                         165
Multi Home Realtors                  162
INFRAMANTRA INDIA PRIVATE LIMITED    154
Provident Capital                    151
Property Master                      134
Onkar real estate solutions          129
ETHOS PRO REALTORS                   123
Thirty Three Estates Developers      121
seller                               113
Surendra Realtors                    113
HOMZ SOLUTIONS                       110
Individual Agent                     109
Name: count, dtype: int64

In [ ]:
# Lets drop builders name (won't affect much)

# The model would learn

# Locality → Price
# Area → Price
# BHK → Price
# Society → Price
# Builder (M3M, DLF, Godrej) → Price

# It should not learn:

# "This property was listed by Sharma Prop."

# .value count shows how in how many rows did the value appear and the top 20 of em

In [ ]:
# value_counts() is not used to remove features directly.
# It is an EDA (Exploratory Data Analysis) tool that helps us decide whether a feature is useful or not.

In [ ]:
data["Company Name"].value_counts().head(20) # useful

Company Name
M3M          1845
Outside      1277
Godrej        790
DLF           710
Signature     633
Krisumi       386
Ireo          380
Sobha         356
BPTP          344
Whiteland     320
Emaar         304
Birla         257
Smart         243
SS            234
Puri          229
Vatika        215
Adani         194
Elan          185
Experion      182
Bestech       175
Name: count, dtype: int64

In [ ]:
# Cleaning
data["Price"].head()

0    10700000.0
1    14400000.0
2    10700000.0
3    40000000.0
4    24000000.0
Name: Price, dtype: str

In [ ]:
data["Rate per sqft"].head()

0     9,450
1     9,450
2     9,450
3     8,888
4    13,333
Name: Rate per sqft, dtype: str

In [ ]:
 # data["Price"]=data["Price"].astype(float)
# error

In [ ]:
data["Price"]=data["Price"].str.strip()

In [ ]:
data["Price"] = data["Price"].str.replace(",", "")

In [ ]:
data["Price"]=data["Price"].astype(float)

In [ ]:
data["Rate per sqft"]=data["Rate per sqft"].str.strip()

In [ ]:
data["Rate per sqft"]=data["Rate per sqft"].str.replace(",","")

In [ ]:
data["Rate per sqft"]=data["Rate per sqft"].astype(float)

In [ ]:
data.info()

<class 'pandas.DataFrame'>
Index: 14223 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          14223 non-null  float64
 1   Status         14223 non-null  str
 2   Area           14223 non-null  int64
 3   Rate per sqft  14223 non-null  float64
 4   Property Type  14223 non-null  str
 5   Locality       14223 non-null  str
 6   Builder Name   14223 non-null  str
 7   RERA Approval  14223 non-null  str
 8   BHK_Count      14223 non-null  float64
 9   Socity         14223 non-null  str
 10  Company Name   14223 non-null  str
 11  Flat Type      14223 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 3.2 MB

In [ ]:
# Raw dataset
#     |
#     ↓
# Remove duplicates ✅ 
#     |
#     ↓
# Fix data types (✅)
#     |
#     ↓
# Handle categorical features
#     |
#     ↓
# Train model

# (Try removing features as well)
# (Not skewed distrbution)
# (Find errors in data)

In [ ]:
data.describe()

              Price           Area  Rate per sqft     BHK_Count
count  1.422300e+04   14223.000000   14223.000000  14223.000000
mean   3.995377e+07    2621.755959   15296.143992      3.266189
std    5.755291e+07   11125.298077   18761.002333      5.496692
min    9.500000e+04      60.000000     100.000000      0.000000
25%    1.410000e+07    1424.000000    8368.000000      2.000000
50%    2.620000e+07    2015.000000   12380.000000      3.000000
75%    4.550000e+07    2840.500000   18500.000000      4.000000
max    1.226300e+09  958320.000000  310000.000000    132.000000

In [ ]:
# Price looks normal
# Rest all have outliers see the max value

In [ ]:
# data.loc is a pandas method used to select rows and columns by labels or conditions.

In [ ]:
data.loc[data["BHK_Count"] > 10].sum()

Price                                                 1611050000.0
Status           ResaleResaleResaleNewNewNewNewNewNewNewNewNewN...
Area                                                        187258
Rate per sqft                                             566146.0
Property Type    Residential Plot in Reputed Builder Plot Secto...
Locality         Sector 39Sector 112Sector 112Sector 102Sector ...
Builder Name     Property In GurgaonInvestor's LandbaseDream Ho...
RERA Approval    Not approved by RERANot approved by RERANot ap...
BHK_Count                                                   4441.0
Socity            Reputed Builder Plot Sector 39 Rishali Luxe R...
Company Name     ReputedRishaliRishaliBPTPUppalUppalUppalUppalU...
Flat Type        PlotPlotPlotPlotPlotPlotPlotPlotPlotPlotPlotPl...
dtype: object

In [ ]:
data.loc[data["BHK_Count"] > 10, ["Price", "Area", "BHK_Count", "Flat Type"]].info()

<class 'pandas.DataFrame'>
Index: 52 entries, 141 to 19467
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      52 non-null     float64
 1   Area       52 non-null     int64
 2   BHK_Count  52 non-null     float64
 3   Flat Type  52 non-null     str
dtypes: float64(2), int64(1), str(1)
memory usage: 2.2 KB

In [ ]:
# What should we do?

# We have two options:
# 1)  Option 1 (Recommended): Fix these values
    #   because plots have no bedrooms.
# 2)  Option 2: Remove rows 
    # I would not remove these rows because:
    # Plot properties are valuable for a Delhi/Gurgaon real estate predictor.
    # They contribute price information.

In [ ]:
data.loc[data["Flat Type"]=="Plot", "BHK_Count"].describe()

count    2166.000000
mean        3.734072
std        13.922033
min         0.000000
25%         0.000000
50%         2.000000
75%         3.000000
max       132.000000
Name: BHK_Count, dtype: float64

In [ ]:
data.loc[data["Flat Type"]=="Plot", "BHK_Count"].info()

<class 'pandas.Series'>
Index: 2166 entries, 3 to 19472
Series name: BHK_Count
Non-Null Count  Dtype
--------------  -----
2166 non-null   float64
dtypes: float64(1)
memory usage: 33.8 KB

In [ ]:
data.loc[data["Flat Type"] == "Plot", "BHK_Count"] = 0

In [ ]:
data.loc[data["Flat Type"]=="Plot", "BHK_Count"].describe()

count    2166.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: BHK_Count, dtype: float64

In [ ]:
data.loc[
    (data["Flat Type"]=="House") & (data["BHK_Count"]>10)
]

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
17125,175000000.0,Ready to move,15000,11666.0,15 BHK Independent House in LUXURY kothi,DLF Phase 3,Sharma Prop,Not approved by RERA,15.0,LUXURY kothi,LUXURY,House
17133,90000000.0,Ready to move,9600,9375.0,12 BHK Independent House in LUXURY floorsss,DLF Phase 3,Sharma Prop,Not approved by RERA,12.0,LUXURY floorsss,LUXURY,House
17375,38700000.0,Ready to move,7525,5142.0,15 BHK Independent House in house,Sector 17A,home,Not approved by RERA,15.0,house,house,House

In [ ]:
data.loc[data["Area"] > 50000]

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
12102,90000000.0,Resale,87300,1030.0,Residential Plot,Sector 75,Shiva Homz,Not approved by RERA,0.0,Outside Socity,Outside,Plot
17327,500000000.0,Resale,435600,1147.0,Residential Plot,Baliawas,Deepak property,Not approved by RERA,0.0,Outside Socity,Outside,Plot
17364,119700000.0,Resale,958320,125.0,Residential Plot,37D Dwarka Exp Gurgaon,Sharma Prop,Not approved by RERA,0.0,Outside Socity,Outside,Plot
17455,500000000.0,Resale,435600,1147.0,Residential Plot,Baliawas,home,Not approved by RERA,0.0,Outside Socity,Outside,Plot
17799,750000000.0,Resale,653400,1147.0,Residential Plot in Baliawas farms,Baliawas,Sharma Prop,Not approved by RERA,0.0,Baliawas farms,Baliawas,Plot

In [ ]:
data.describe()

              Price           Area  Rate per sqft     BHK_Count
count  1.422300e+04   14223.000000   14223.000000  14223.000000
mean   3.995377e+07    2621.755959   15296.143992      2.697532
std    5.755291e+07   11125.298077   18761.002333      1.405755
min    9.500000e+04      60.000000     100.000000      0.000000
25%    1.410000e+07    1424.000000    8368.000000      2.000000
50%    2.620000e+07    2015.000000   12380.000000      3.000000
75%    4.550000e+07    2840.500000   18500.000000      4.000000
max    1.226300e+09  958320.000000  310000.000000     15.000000

In [ ]:
# Your dataset contains different property types: (for area)

# Flat Type	Meaning of Area
# Apartment	Built-up/super area
# House	    Built-up area
# Plot	    Land area

# so all area do not mean the same thing

# What I would do:
# 1. Keep Area as it is
# 2. Add a feature indicating plot
# data["Is_Plot"] = (data["Flat Type"] == "Plot").astype(int)
# 3. Later apply log transformation to Area Because Area is highly skewed:
# median Area = 2015
# max Area = 958320

# Is_Plot feature (adding information)
# This is about giving the model context.
# The model understands:
# "This large area is because it is land."

# Tree models (Random Forest, XGBoost) are less sensitive to skewness than linear models.

In [ ]:
data["Is_Plot"] = (data["Flat Type"] == "Plot").astype(int)

In [ ]:
data["Area"] = np.log1p(data["Area"]) # log(x+1)
# remember at time of deployment the area input from user shall also be logged.

In [ ]:
# Everything we are doing right now comes under Data Preprocessing (more specifically, Data Cleaning + Feature Engineering).

In [ ]:
# Raw Data
#    |
#    ↓
# 1. Data Understanding / EDA
#    |
#    ↓
# 2. Data Cleaning  ← we did this
#    - Fix data types
#    - Handle missing values
#    - Remove duplicates
#    - Correct invalid values
#    |
#    ↓
# 3. Exploratory Data Analysis (EDA) ← we are here too
#    - Histograms
#    - Outlier investigation
#    - Distribution analysis
#    - Understanding relationships
#    |
#    ↓
# 4. Feature Engineering ← we started this
#    - Creating Is_Plot
#    - Log transformation of Area
#    - Selecting useful features
#    |
#    ↓
# 5. Feature Encoding
#    - One-hot encoding
#    - Label encoding (if needed)
#    |
#    ↓
# 6. Model Training
#    - Train/test split
#    - Algorithms
#    - Evaluation

In [ ]:
# outlier analysis + data cleaning/feature improvement.(currently)

In [ ]:
# now for rate pr sqft

In [ ]:
data["Rate per sqft"].describe()

count     14223.000000
mean      15296.143992
std       18761.002333
min         100.000000
25%        8368.000000
50%       12380.000000
75%       18500.000000
max      310000.000000
Name: Rate per sqft, dtype: float64

In [ ]:
# This is right skewed

In [ ]:
data.loc[data["Rate per sqft"]>100000]
# This is valid but skewed

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type,Is_Plot
97,286000000.0,Under Construction,7.170888,220000.0,2 BHK Apartment in M3M Capital,Sector 113,Vijayata Enterprises,Approved by RERA,2.0,M3M Capital,M3M,Apartment,0
242,286000000.0,Under Construction,7.170888,220000.0,2 BHK Apartment in M3M Capital,Sector 113,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Capital,M3M,Apartment,0
243,292600000.0,Under Construction,7.193686,220000.0,2 BHK Apartment in M3M Capital,Sector 113,Khushi Housing Solutions Pvt Ltd,Approved by RERA,2.0,M3M Capital,M3M,Apartment,0
244,453200000.0,Under Construction,7.630947,220000.0,4 BHK Apartment in M3M Capital,Sector 113,Khushi Housing Solutions Pvt Ltd,Approved by RERA,4.0,M3M Capital,M3M,Apartment,0
245,366300000.0,Under Construction,7.418181,220000.0,3 BHK Apartment in M3M Capital,Sector 113,Khushi Housing Solutions Pvt Ltd,Approved by RERA,3.0,M3M Capital,M3M,Apartment,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16018,494700000.0,Under Construction,7.718685,220000.0,4 BHK Apartment in M3M Capital,Sector 113,Growmax Wealth Management Services,Approved by RERA,4.0,M3M Capital,M3M,Apartment,0
16019,363000000.0,Under Construction,7.409136,220000.0,3 BHK Apartment in M3M Capital,Sector 113,Growmax Wealth Management Services,Approved by RERA,3.0,M3M Capital,M3M,Apartment,0
16020,374000000.0,Under Construction,7.438972,220000.0,3 BHK Apartment in M3M Capital,Sector 113,Growmax Wealth Management Services,Approved by RERA,3.0,M3M Capital,M3M,Apartment,0
16021,372900000.0,Under Construction,7.436028,220000.0,3 BHK Apartment in M3M Capital,Sector 113,Growmax Wealth Management Services,Approved by RERA,3.0,M3M Capital,M3M,Apartment,0
17519,185000000.0,Ready to move,7.520776,100271.0,3 BHK Apartment in HUDA Plot Sector 57,Sector 57,Bob vennikal,Not approved by RERA,3.0,HUDA Plot Sector 57,HUDA,Apartment,0

In [ ]:
# Transforming features (Area, Rate per sqft) → helps the input representation.
# Transforming target (Price) → helps the model learn the output distribution.
# it depends on the model, but for regression projects it is often useful to transform the target variable too.

In [ ]:
data["Rate per sqft"].skew()

np.float64(8.93030220101966)

In [ ]:
# If it is high (>1), apply:
data["Rate per sqft"] = np.log1p(data["Rate per sqft"])

In [ ]:
data["Rate per sqft"].skew()

np.float64(0.09137778011693583)

In [ ]:
# Feature	                       Decision
# BHK_Count	             Fix plots → 0, keep luxury houses
# Area	                  Keep large plots, log transform
# Rate per sqft	       Keep luxury properties, log transform

In [ ]:
data["Price"].describe()

count    1.422300e+04
mean     3.995377e+07
std      5.755291e+07
min      9.500000e+04
25%      1.410000e+07
50%      2.620000e+07
75%      4.550000e+07
max      1.226300e+09
Name: Price, dtype: float64

In [ ]:
data["Price"].skew()

np.float64(7.656266338590509)

In [ ]:
data.loc[data["Price"] > 500000000, ["Price", "Area", "Flat Type", "Property Type", "Locality"]]

,Price,Area,Flat Type,Property Type,Locality
246,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
873,6.500000e+08,8.881420,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
2141,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
2828,6.689000e+08,9.105091,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
2829,8.175000e+08,9.305741,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
2830,5.476000e+08,8.905173,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2831,5.470000e+08,8.904087,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2832,5.462000e+08,8.902592,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2833,9.768000e+08,9.483721,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
2834,5.348000e+08,8.881420,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2835,5.522000e+08,8.913416,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2836,5.711000e+08,8.947156,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2837,7.000000e+08,9.150590,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
2838,9.662000e+08,9.472782,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
2839,1.226300e+09,9.711176,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
2840,5.499000e+08,8.909370,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
2841,1.189100e+09,9.680406,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
2842,7.060000e+08,9.159152,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
2843,9.352000e+08,9.440261,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
2906,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
6118,5.476000e+08,8.905173,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
6119,5.470000e+08,8.904087,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
6120,5.462000e+08,8.902592,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
6121,9.768000e+08,9.483721,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
7186,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
8638,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
10328,9.662000e+08,9.472782,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
10329,7.000000e+08,9.150590,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
10367,5.499000e+08,8.909370,Apartment,4 BHK Apartment in DLF Camellias,Sector 42
10399,9.352000e+08,9.440261,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
10419,1.226300e+09,9.711176,Apartment,6 BHK Apartment in DLF Camellias,Sector 42
10460,9.352000e+08,9.440261,Apartment,5 BHK Apartment in DLF Camellias,Sector 42
14312,5.202000e+08,9.124347,Apartment,5 BHK Apartment in DLF Magnolias,Sector 42
16014,5.055000e+08,7.740230,Apartment,4 BHK Apartment in M3M Capital,Sector 113
16974,5.100000e+08,9.350189,Penthouse,7 BHK Penthouse in Dlf camelliaass,Golf Course Road
17050,5.100000e+08,9.350189,Apartment,7 BHK Apartment in DLF Camellias,Sector 42
17153,6.000000e+08,9.350189,Penthouse,7 BHK Penthouse in Camelliaass,Golf Course Road
17195,5.100000e+08,9.350189,Apartment,7 BHK Apartment in DLF Camellias,Sector 42
17799,7.500000e+08,13.389946,Plot,Residential Plot in Baliawas farms,Baliawas

In [ ]:
data["log_price"] = np.log1p(data["Price"])

In [ ]:
# Better:

# data["log_price"] = np.log1p(data["Price"])

# Then:

# X = data.drop("Price", axis=1)
# y = data["log_price"]

# During prediction:

# predicted_price = np.expm1(predicted_log_price)

In [ ]:
# So numerical analysis is now almost complete:

# | Feature       | Action                      |
# | ------------- | --------------------------- |
# | BHK_Count     | Fix Plot → 0                |
# | Area          | Keep + log transform        |
# | Rate per sqft | Keep + likely log transform |
# | Price         | Keep + log transform target |

In [ ]:
# Next phase:
# Categorical feature analysis

# Feature Engineering
#         ↓
# Train-test split
#         ↓
# Preprocessing pipeline
#         ↓
# Model training

In [ ]:
# | Skewness value | Meaning                |
# | -------------- | ---------------------- |
# | Around 0       | Symmetric distribution |
# | > 0            | Right skew             |
# | < 0            | Left skew              |
# | > 1            | Highly skewed          |

In [ ]:
data.describe()

,Price,Area,Rate per sqft,BHK_Count,Is_Plot,log_price
count,1.422300e+04,14223.000000,14223.000000,14223.000000,14223.000000,14223.000000
mean,3.995377e+07,7.622188,9.401795,2.697532,0.152289,17.024891
std,5.755291e+07,0.608473,0.630101,1.405755,0.359313,1.002991
min,9.500000e+04,4.110874,4.615121,0.000000,0.000000,11.461643
25%,1.410000e+07,7.261927,9.032290,2.000000,0.000000,16.461685
50%,2.620000e+07,7.608871,9.423918,3.000000,0.000000,17.081270
75%,4.550000e+07,7.952087,9.825580,4.000000,0.000000,17.633223
max,1.226300e+09,13.772938,12.644331,15.000000,1.000000,20.927267

In [ ]:
data.nunique()

Price            1758
Status              4
Area             2038
Rate per sqft    3928
Property Type    1848
Locality          245
Builder Name      725
RERA Approval       2
BHK_Count          13
Socity            967
Company Name      269
Flat Type           6
Is_Plot             2
log_price        1758
dtype: int64

In [ ]:
data.columns

Index(['Price', 'Status', 'Area', 'Rate per sqft', 'Property Type', 'Locality',
       'Builder Name', 'RERA Approval', 'BHK_Count', 'Socity', 'Company Name',
       'Flat Type', 'Is_Plot', 'log_price'],
      dtype='str')

In [ ]:
data

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type,Is_Plot,log_price
0,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.185754
1,14400000.0,Under Construction,7.332369,9.153876,3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.482739
2,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.185754
3,40000000.0,Ready to move,8.412055,9.092570,4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,0.0,Outside Socity,Outside,Plot,1,17.504390
4,24000000.0,Under Construction,7.496097,9.498072,3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor,0,16.993564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19510,24100000.0,Ready to move,7.231287,9.770013,2 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,2.0,Sobha City,Sobha,Apartment,0,16.997722
19511,36200000.0,Ready to move,7.636752,9.770013,3 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,3.0,Sobha City,Sobha,Apartment,0,17.404570
19512,39100000.0,Under Construction,7.802209,9.680531,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.481633
19513,37700000.0,Under Construction,7.766841,9.680469,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.445171
19514,36500000.0,Under Construction,7.733246,9.680719,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.412823

In [ ]:
# rera;flattype;status

# not to encode them together # pd.get_dummies(data["RERA Approval"],drop_first=True)

# Suppose you keep all three dummy columns.
# Ready + Resale + Under Construction = 1
# This creates perfect multicollinearity (the dummy variable trap). 
# The model can't uniquely estimate the coefficients because one column is an exact linear combination of the others.
# Dropping one dummy solves this.


# For Tree-Based Models (Random Forest, XGBoost)
# Tree models do not suffer from this problem.
# So:
# drop_first=True is not required for Random Forest, XGBoost, Decision Trees.
# It is still okay to use, but many practitioners simply keep all dummy columns with tree models.

# so short summary the coefficent exchange might lead to same answer
#  if all one hot features are there but with a dropped featture model understands the parameters better
# This is mainly important for Linear Regression-type models.

In [ ]:
data

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type,Is_Plot,log_price
0,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.185754
1,14400000.0,Under Construction,7.332369,9.153876,3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.482739
2,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment,0,16.185754
3,40000000.0,Ready to move,8.412055,9.092570,4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,0.0,Outside Socity,Outside,Plot,1,17.504390
4,24000000.0,Under Construction,7.496097,9.498072,3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor,0,16.993564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19510,24100000.0,Ready to move,7.231287,9.770013,2 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,2.0,Sobha City,Sobha,Apartment,0,16.997722
19511,36200000.0,Ready to move,7.636752,9.770013,3 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,3.0,Sobha City,Sobha,Apartment,0,17.404570
19512,39100000.0,Under Construction,7.802209,9.680531,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.481633
19513,37700000.0,Under Construction,7.766841,9.680469,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.445171
19514,36500000.0,Under Construction,7.733246,9.680719,3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment,0,17.412823

In [ ]:
data.nunique().sort_values()

RERA Approval       2
Is_Plot             2
Status              4
Flat Type           6
BHK_Count          13
Locality          245
Company Name      269
Builder Name      725
Socity            967
log_price        1758
Price            1758
Property Type    1848
Area             2038
Rate per sqft    3928
dtype: int64

In [ ]:
# | Column        | Action                     |
# | ------------- | -------------------------- |
# | RERA Approval | ✅ One-hot                  |
# | Status        | ✅ One-hot                  |
# | Flat Type     | ✅ One-hot                  |
# | Is_Plot       | ✅ Keep                     |
# | Locality      | ✅ One-hot                  |
# | Company Name  | ✅ One-hot                  |
# | Builder Name  | ❌ Drop                     |
# | Socity        | ⚠️ Top categories + Others |

In [ ]:
# Categorical Feature Handling Summary

# 1. Low Cardinality Features
# --------------------------------
# Meaning:
# - Features with a small number of unique categories.
# - Safe to apply One-Hot Encoding directly.

# Examples in our dataset:

# RERA Approval (2 values)
# - Approved by RERA
# - Not approved by RERA

# Action:
# ✅ Keep
# ✅ One-hot encode


# Status (4 values)
# - Ready to move
# - Under Construction
# - Resale
# - ...

# Action:
# ✅ Keep
# ✅ One-hot encode


# Flat Type (6 values)
# - Apartment
# - House
# - Plot
# - Penthouse
# - ...

# Action:
# ✅ Keep
# ✅ One-hot encode


# Is_Plot (2 values)
# - Already converted into 0/1

# Action:
# ✅ Keep
# ❌ No encoding required


# ------------------------------------------------

# 2. Medium Cardinality Features
# --------------------------------
# Meaning:
# - Features with a moderate number of unique categories.
# - Need to check whether they carry useful information.
# - One-hot encoding is possible if the dataset is large enough.

# Locality (245 values)

# Reason to keep:
# - Location is one of the strongest factors affecting property price.
# - Different sectors have different price ranges.

# Action:
# ✅ Keep
# ✅ One-hot encode


# Company Name (269 values)

# Reason to keep:
# - Builder/brand reputation affects property value.
# - Examples:
#   M3M, DLF, Godrej, Sobha

# Action:
# ✅ Keep
# ✅ One-hot encode


# ------------------------------------------------

# 3. High Cardinality Features
# --------------------------------
# Meaning:
# - Features with many unique categories.
# - Direct one-hot encoding can create too many columns.
# - May increase sparsity and overfitting.

# Builder Name (725 values)

# Observation:
# - Many values are not actual builders.
# - Examples:
#   home
#   Property In Gurgaon
#   properties for sale in Gurgaon

# Problem:
# - Contains broker/agent names and noisy information.

# Action:
# ❌ Drop


# Socity (967 values)

# Observation:
# - Unlike Builder Name, Society contains useful information.
# - Examples:
#   DLF Camellias
#   M3M Capital
#   Godrej Air

# Problem:
# - Too many categories.

# Possible solutions:

# Option 1:
# One-hot encode all categories.

# Option 2 (better):
# Keep only top N societies and group the rest as "Others".

# Action:
# ⚠️ Keep
# ⚠️ Reduce categories before encoding


# ------------------------------------------------

# Final Feature Decisions

# Keep:
# ✅ RERA Approval
# ✅ Status
# ✅ Flat Type
# ✅ Is_Plot
# ✅ Locality
# ✅ Company Name
# ✅ Socity (after reducing categories)

# Drop:
# ❌ Builder Name


# Encoding Plan:

# One-hot encode:
# - RERA Approval
# - Status
# - Flat Type
# - Locality
# - Company Name
# - Socity

# Keep as numerical:
# - Area
# - Rate per sqft
# - BHK_Count
# - Is_Plot
# - log_price (target)

In [ ]:
# Lets understand socity
# Approach: Keep top societies, group the rest
data["Socity"].value_counts()

Socity
Outside Socity                      1277
 M3M Golf Estate                     509
 Krisumi Waterfall Residences        315
 Whiteland The Aspen                 283
 Birla Navya Gurugram                252
                                    ...
 Sushant lok 2 Sector 57 Gurgaon       1
 Unitech Uniworld Gardens              1
 Vipul Aarohan                         1
 AB Realty Valencia                    1
 I block 132                           1
Name: count, Length: 967, dtype: int64

In [ ]:
socity_counts = data["Socity"].value_counts()
common_societies = socity_counts[socity_counts > 50].index

In [ ]:
common_societies

Index(['Outside Socity', ' M3M Golf Estate', ' Krisumi Waterfall Residences',
       ' Whiteland The Aspen', ' Birla Navya Gurugram', ' Godrej Air',
       ' Ireo Victory Valley', ' M3M Capital', ' Elan The Presidential',
       ' M3M M3M Crown', ' Sobha City Vista Residences', ' M3M Merl',
       ' BPTP Terra', ' M3M Heights', ' M3M Sierra 68', ' Godrej Meridien',
       ' Sobha City', ' Godrej Aristocrat', ' M3M Antalya Hills ',
       ' DLF The Crest', ' M3M Golf Hills Phase 1',
       ' Signature Global City 93', ' Navraj The Antalya', ' Conscient H',
       ' Adani M2K Oyster Grande', ' Smart Smartworld One DXP',
       ' Puri Diplomatic Residences', ' Tata Primanti',
       ' Shapoorji Pallonji JoyVille', ' M3M Mansion', ' Ireo The Grand Arch',
       ' Signature Global Deluxe DXP', ' SS The Leaf', ' SS L', ' Paras Dews',
       ' Experion W', ' Tulip Monsella', ' Pioneer Araya', ' LUXURY floorsss',
       ' Krisumi Waterside Residence', ' Smart Smart World Gems',
       ' Ambience Creacions', ' Eldeco Accolade', ' Godrej 101',
       ' Bestech Park View Altura', ' Experion The Heartsong',
       ' Godrej Zenith', ' Hero Homes Gurgaon', ' M3M Skycity',
       ' B kumar and brothers the passion group',
       ' Signature Global City 79 B', ' Barga', ' DLF The Arbour',
       ' Puri Diplomatic Greens', ' Ashiana Anmol', ' Ganga Nandaka'],
      dtype='str', name='Socity')

In [ ]:
socity_counts

Socity
Outside Socity                      1277
 M3M Golf Estate                     509
 Krisumi Waterfall Residences        315
 Whiteland The Aspen                 283
 Birla Navya Gurugram                252
                                    ...
 Sushant lok 2 Sector 57 Gurgaon       1
 Unitech Uniworld Gardens              1
 Vipul Aarohan                         1
 AB Realty Valencia                    1
 I block 132                           1
Name: count, Length: 967, dtype: int64

In [ ]:
data["Socity"]=data["Socity"].apply(lambda x: x if x in common_societies else "Other")

In [ ]:
data["Socity"].nunique()

57

In [ ]:
data["Socity"].value_counts()

Socity
Other                                      6921
Outside Socity                             1277
 M3M Golf Estate                            509
 Krisumi Waterfall Residences               315
 Whiteland The Aspen                        283
 Birla Navya Gurugram                       252
 Godrej Air                                 230
 Ireo Victory Valley                        204
 M3M Capital                                201
 Elan The Presidential                      183
 M3M M3M Crown                              160
 Sobha City Vista Residences                138
 M3M Merl                                   126
 BPTP Terra                                 114
 M3M Heights                                113
 M3M Sierra 68                              113
 Godrej Meridien                            112
 Sobha City                                 109
 Godrej Aristocrat                          108
 M3M Antalya Hills                          107
 DLF The Crest                              103
 M3M Golf Hills Phase 1                      97
 Signature Global City 93                    97
 Navraj The Antalya                          94
 Conscient H                                 94
 Adani M2K Oyster Grande                     94
 Smart Smartworld One DXP                    91
 Puri Diplomatic Residences                  90
 Tata Primanti                               89
 Shapoorji Pallonji JoyVille                 87
 M3M Mansion                                 82
 Ireo The Grand Arch                         82
 Signature Global Deluxe DXP                 79
 SS The Leaf                                 76
 SS L                                        75
 Paras Dews                                  71
 Experion W                                  68
 Tulip Monsella                              67
 Pioneer Araya                               66
 LUXURY floorsss                             66
 Krisumi Waterside Residence                 62
 Smart Smart World Gems                      61
 Ambience Creacions                          61
 Eldeco Accolade                             61
 Godrej 101                                  60
 Bestech Park View Altura                    60
 Experion The Heartsong                      60
 Godrej Zenith                               60
 Hero Homes Gurgaon                          60
 M3M Skycity                                 58
 B kumar and brothers the passion group      57
 Signature Global City 79 B                  56
 Barga                                       55
 DLF The Arbour                              53
 Puri Diplomatic Greens                      53
 Ashiana Anmol                               52
 Ganga Nandaka                               51
Name: count, dtype: int64

In [ ]:
data.drop(columns=["Builder Name"], inplace=True)

In [ ]:
data

,Price,Status,Area,Rate per sqft,Property Type,Locality,RERA Approval,BHK_Count,Socity,Company Name,Flat Type,Is_Plot,log_price
0,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Approved by RERA,2.0,Other,M3M,Apartment,0,16.185754
1,14400000.0,Under Construction,7.332369,9.153876,3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Approved by RERA,3.0,Other,M3M,Apartment,0,16.482739
2,10700000.0,Under Construction,7.037906,9.153876,2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Approved by RERA,2.0,Other,M3M,Apartment,0,16.185754
3,40000000.0,Ready to move,8.412055,9.092570,4 BHK Independent Floor,Sector 57,Not approved by RERA,0.0,Outside Socity,Outside,Plot,1,17.504390
4,24000000.0,Under Construction,7.496097,9.498072,3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,Approved by RERA,3.0,Other,Anant,Floor,0,16.993564
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19510,24100000.0,Ready to move,7.231287,9.770013,2 BHK Apartment in Sobha City,Sector 108,Not approved by RERA,2.0,Sobha City,Sobha,Apartment,0,16.997722
19511,36200000.0,Ready to move,7.636752,9.770013,3 BHK Apartment in Sobha City,Sector 108,Not approved by RERA,3.0,Sobha City,Sobha,Apartment,0,17.404570
19512,39100000.0,Under Construction,7.802209,9.680531,3 BHK Apartment in Pyramid Alban,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.481633
19513,37700000.0,Under Construction,7.766841,9.680469,3 BHK Apartment in Pyramid Alban,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.445171
19514,36500000.0,Under Construction,7.733246,9.680719,3 BHK Apartment in Pyramid Alban,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.412823

In [ ]:
data.drop(columns=["Property Type"], inplace=True)

In [ ]:
# cat_cols = [
#     "RERA Approval",
#     "Status",
#     "Flat Type",
#     "Locality",
#     "Company Name",
#     "Socity"
# ]
data.columns

Index(['Price', 'Status', 'Area', 'Rate per sqft', 'Locality', 'RERA Approval',
       'BHK_Count', 'Socity', 'Company Name', 'Flat Type', 'Is_Plot',
       'log_price'],
      dtype='str')

In [ ]:
data

,Price,Status,Area,Rate per sqft,Locality,RERA Approval,BHK_Count,Socity,Company Name,Flat Type,Is_Plot,log_price
0,10700000.0,Under Construction,7.037906,9.153876,Sector 79,Approved by RERA,2.0,Other,M3M,Apartment,0,16.185754
1,14400000.0,Under Construction,7.332369,9.153876,Sector 79,Approved by RERA,3.0,Other,M3M,Apartment,0,16.482739
2,10700000.0,Under Construction,7.037906,9.153876,Sector 79,Approved by RERA,2.0,Other,M3M,Apartment,0,16.185754
3,40000000.0,Ready to move,8.412055,9.092570,Sector 57,Not approved by RERA,0.0,Outside Socity,Outside,Plot,1,17.504390
4,24000000.0,Under Construction,7.496097,9.498072,Sector 63,Approved by RERA,3.0,Other,Anant,Floor,0,16.993564
...,...,...,...,...,...,...,...,...,...,...,...,...
19510,24100000.0,Ready to move,7.231287,9.770013,Sector 108,Not approved by RERA,2.0,Sobha City,Sobha,Apartment,0,16.997722
19511,36200000.0,Ready to move,7.636752,9.770013,Sector 108,Not approved by RERA,3.0,Sobha City,Sobha,Apartment,0,17.404570
19512,39100000.0,Under Construction,7.802209,9.680531,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.481633
19513,37700000.0,Under Construction,7.766841,9.680469,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.445171
19514,36500000.0,Under Construction,7.733246,9.680719,Sector 71,Approved by RERA,3.0,Other,Pyramid,Apartment,0,17.412823

In [ ]:
cat_cols = [
    "RERA Approval",
    "Status",
    "Flat Type",
    "Locality",
    "Company Name",
    "Socity"
]
data=pd.get_dummies(data,columns=cat_cols,drop_first=True,dtype=int)

In [ ]:
data.shape

(14223, 583)

In [ ]:
data.info()

<class 'pandas.DataFrame'>
Index: 14223 entries, 0 to 19514
Columns: 583 entries, Price to Socity_Outside Socity
dtypes: float64(5), int64(578)
memory usage: 63.4 MB

In [ ]:
# The orignal columns will automatically be removed after one hot encoding

In [ ]:
data.select_dtypes(include="object").columns # no categorical

Index([], dtype='str')

In [ ]:
data.isnull().sum().sum()

np.int64(0)

In [ ]:
X = data.drop(columns=["Price", "log_price"])
y = data["log_price"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
# ///////////  # EDA is complete   ////////////

In [ ]:
# Your first baseline should be:

# Linear Regression (sanity check)
# Random Forest Regressor
# Gradient Boosting / XGBoost

# Then compare:

# MAE
# RMSE
# R²

In [ ]:
# | Metric | Meaning                | Effect of large errors         |
# | ------ | ---------------------- | ------------------------------ |
# | MAE    | Average absolute error | Treats all errors equally      |
# | MSE    | Average squared error  | Penalizes large errors heavily |
# | RMSE   | Square root of MSE     | Same units as target           |

In [ ]:
# Raw Data
#    |
#    ↓
# Clean values
#    |
#    ↓
# Log transform Area
#    |
#    ↓
# Log transform Rate per sqft
#    |
#    ↓
# Create Is_Plot
#    |
#    ↓
# Create log_price target
#    |
#    ↓
# Reduce Socity categories
#    |
#    ↓
# One-hot encode categorical features
#    |
#    ↓
# Model training

# For a first serious ML project, this is already a solid amount of feature engineering.

# Next step after encoding is 
# not more feature engineering — it is building a baseline model and seeing what performance you get. Then we improve based on errors.

In [ ]:
data.select_dtypes(include="object").columns

Index([], dtype='str')

In [ ]:
data.to_csv("processed_house_data.csv", index=False)

In [ ]:
data